.gitignore, .travis.yml
travis finished.
tests run with this versions of python3: .5, .6, .7, .8 and pypy3.
tests run with those versions combined with this versions of django: 2.2 and 3.07
=> Travis config

.codeclimate.yml, drip/admin.py, drip/drips.py, drip/helpers.py, drip/models.py, drip/tests/test_custom_messages.py, drip/tests/test_drips.py, drip/tests/test_rules.py, drip/utils.py
- Codeclimate configuration.
- Ignore folders that don't correspond to analyze.
- Ignore duplication checks on tests.
- Rise default threshold for parameters and number of functions in a class 
- Check pep8.
- Changes to improve codeclimate score: split test file in three different files with different test cases, reduce complexity in functions.
- Three issues are going to be ignored: a duplication in code and a test case with too many lines.
=> Improve CodeClimate

.travis.yml, README.md
Setup to integrate test coverage with codeclimate and travis
=> travis configuration for test coverage in codeclimate

.travis.yml, README.md
Error in Readme.md
Test reporter isn't showing the coverage
=> Fix travis-codeclimate test reporter

drip/tests/test_drips.py
Add url tests to be sure we are not changing urls in #26
=> Add url tests

drip/admin.py, drip/drips.py, drip/helpers.py, drip/models.py, drip/tests/test_custom_messages.py, drip/tests/test_drips.py, drip/tests/test_rules.py, drip/utils.py
=> Change indentation according to standard definition

docs/source/content/classes.rst, docs/source/content/create.drip.rst, docs/source/drip.management.commands.rst, docs/source/drip.management.rst, docs/source/drip.rst, docs/source/index.rst
Added autodoc generated with sphinx with the specification of the classes.
TODO:
- Review and Improve docstrings documentation
=> Class specification in docs

Pipfile, Pipfile.lock, setup.py
Closes #44 
Change `setup.py` to set the `README` file as. 
In the next build of the package, the README will be shown in django-drip-campaigns pypi page
=> Pypi doc in setup

CONTRIBUTING.md
Add definition of string formatting in CONTRIBUTING.md to explain that to the contributors
=> Add string formatting specification

.gitignore, Pipfile, Pipfile.lock, README.md, drip/management/commands/send_drips.py, drip/scheduler/cron_scheduler.py, setup.py
- A feature to easily configure cron.
- You can add now some parameters in your settings to send drips automatically and periodically.
- It uses python appscheduler.
- Explanation added in README.
- It was manually tested with test-pypi.
=> Add feature of cron scheduler

README.md, docs/source/content/features.rst
- Minor fix at README
- Add sphinx documentation for cron scheduler feature
=> Sphinx documentation for cron scheduler

drip/models.py
Make actual models abstract so field overrides are possible
Make Base models to maintain compatibility
=> [feat] make all models extensible by inheritance

Pipfile, Pipfile.lock, docs/source/conf.py, docs/source/content/create.drip.rst, docs/source/content/extending.rst, docs/source/index.rst, drip/models.py, drip/types.py
Docs for the recent functionality
Minor changes in pipfile to solve error on pipenv install dependency.
Minor change on config file of docs, to solve warning
=> add docs for or use and how to extend django drip

.github/workflows/drip-deployment.yaml
Fix github actions script to deploy to Pipy. Build dist folder.
=> Fix deployment action, build dist folder

CONTRIBUTING.md, Pipfile.lock, README.md
Remove travis from docs and update badge in README
- Github badge
=> Remove travis badge and use github actions

.github/workflows/drip-django.yaml, .pre-commit-config.yaml, Pipfile, Pipfile.lock, docs/source/conf.py, drip/admin.py, drip/drips.py, drip/helpers.py, drip/models.py, drip/tests/test_custom_messages.py, drip/tests/test_drips.py, drip/types.py, drip/utils.py, requirements.txt, setup.cfg
Add mypy stage to pre-commit. 
Make the appropriate tweaks in config to make Mypy work.
Fix existing typing errors for mypy check to be successful.
Fix code, removing unused code for unsupported Python 2.
IMPORTANT:
All ignore comments for mypy will be checked in Typing PR soon.
=> Add mypy stage to pre-commit

.github/workflows/drip-django.yaml, .pre-commit-config.yaml, Pipfile.lock, docs/source/conf.py, drip/admin.py, drip/drips.py, drip/helpers.py, drip/models.py, drip/tests/test_drips.py, drip/utils.py, legacy_docs/conf.py, setup.py
Add missing typing hints for mypy checks. 
There are some ineludible ignores. Mypy is unable to check this lines right.
=> Add missing typing hints for mypy checks

.github/workflows/drip-django.yaml, pytest.ini
Add django 4.0 support, in github actions. Change config in pytest.ini file
=> Add django 4.0 support, in github actions

drip/drips.py, drip/types.py, drip/utils.py
=> Change typing and comments to improve documentation

Pipfile, Pipfile.lock, requirements.txt
Feature/update django version3.2.15
=> Change django version to 3.2.15
